CREATE SCHEMA IF NOT EXISTS quarkus;

CREATE TABLE IF NOT EXISTS CLI_TST (
  ID_CLI BINARY(16) NOT NULL,
  NM_CLI VARCHAR(100) NOT NULL,
  NR_FIL INTEGER,
  DT_NASC DATE NOT NULL,
  DT_CAS DATE,
  TS_INS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_CLI)
);

INSERT INTO quarkus.CLI_TST (ID_CLI, NM_CLI, NR_FIL, DT_NASC, DT_CAS) VALUES (1, "Jonas", 0, '1990-01-01', '2026-01-01');

CREATE TABLE IF NOT EXISTS CNV_CLI_JDCL (
  CD_CLI_MCI BIGINT,
  NR_CVN BIGINT,
  NM_CLI VARCHAR(100) NOT NULL,
  PRIMARY KEY (CD_CLI_MCI, NR_CVN)
);


INSERT INTO quarkus.CNV_CLI_JDCL( CD_CLI_MCI, NR_CVN , NM_CLI) VALUES
(1, 111, "TJSP"),
(2, 222, "TJMT"),
(3, 333, "TJBA");