CREATE SCHEMA IF NOT EXISTS quarkus;

CREATE TABLE IF NOT EXISTS CNV_CLI_JDCL (
  CD_CLI_MCI BIGINT,
  NR_CVN BIGINT,
  NM_CLI VARCHAR(100) NOT NULL,
  PRIMARY KEY (CD_CLI_MCI, NR_CVN)
);

INSERT INTO quarkus.CNV_CLI_JDCL( CD_CLI_MCI, NR_CVN , NM_CLI) VALUES
(1, 111, "TJSP"),
(2, 222, "TJMT"),
(3, 333, "TJBA");